export const COUNTRY_CODES = [
  { name: "Afghanistan", short: "AF", code: "+93" },
  { name: "Albania", short: "AL", code: "+355" },
  { name: "Algeria", short: "DZ", code: "+213" },
  { name: "American Samoa", short: "AS", code: "+1" },
  { name: "Andorra", short: "AD", code: "+376" },
  { name: "Angola", short: "AO", code: "+244" },
  { name: "Anguilla", short: "AI", code: "+1" },
  { name: "Antigua and Barbuda", short: "AG", code: "+1" },
  { name: "Argentina", short: "AR", code: "+54" },
  { name: "Armenia", short: "AM", code: "+374" },
  { name: "Aruba", short: "AW", code: "+297" },
  { name: "Australia", short: "AU", code: "+61" },
  { name: "Austria", short: "AT", code: "+43" },
  { name: "Azerbaijan", short: "AZ", code: "+994" },
  { name: "Bahamas", short: "BS", code: "+1" },
  { name: "Bahrain", short: "BH", code: "+973" },
  { name: "Bangladesh", short: "BD", code: "+880" },
  { name: "Barbados", short: "BB", code: "+1" },
  { name: "Belarus", short: "BY", code: "+375" },
  { name: "Belgium", short: "BE", code: "+32" },
  { name: "Belize", short: "BZ", code: "+501" },
  { name: "Benin", short: "BJ", code: "+229" },
  { name: "Bermuda", short: "BM", code: "+1" },
  { name: "Bhutan", short: "BT", code: "+975" },
  { name: "Bolivia", short: "BO", code: "+591" },
  { name: "Bosnia and Herzegovina", short: "BA", code: "+387" },
  { name: "Botswana", short: "BW", code: "+267" },
  { name: "Brazil", short: "BR", code: "+55" },
  { name: "British Virgin Islands", short: "VG", code: "+1" },
  { name: "Brunei", short: "BN", code: "+673" },
  { name: "Bulgaria", short: "BG", code: "+359" },
  { name: "Burkina Faso", short: "BF", code: "+226" },
  { name: "Burundi", short: "BI", code: "+257" },
  { name: "Cambodia", short: "KH", code: "+855" },
  { name: "Cameroon", short: "CM", code: "+237" },
  { name: "Canada", short: "CA", code: "+1" },
  { name: "Cape Verde", short: "CV", code: "+238" },
  { name: "Cayman Islands", short: "KY", code: "+1" },
  { name: "Central African Republic", short: "CF", code: "+236" },
  { name: "Chad", short: "TD", code: "+235" },
  { name: "Chile", short: "CL", code: "+56" },
  { name: "China", short: "CN", code: "+86" },
  { name: "Colombia", short: "CO", code: "+57" },
  { name: "Comoros", short: "KM", code: "+269" },
  { name: "Congo (Brazzaville)", short: "CG", code: "+242" },
  { name: "Congo (Kinshasa)", short: "CD", code: "+243" },
  { name: "Cook Islands", short: "CK", code: "+682" },
  { name: "Costa Rica", short: "CR", code: "+506" },
  { name: "Croatia", short: "HR", code: "+385" },
  { name: "Cuba", short: "CU", code: "+53" },
  { name: "Cyprus", short: "CY", code: "+357" },
  { name: "Czech Republic", short: "CZ", code: "+420" },
  { name: "Denmark", short: "DK", code: "+45" },
  { name: "Djibouti", short: "DJ", code: "+253" },
  { name: "Dominica", short: "DM", code: "+1" },
  { name: "Dominican Republic", short: "DO", code: "+1" },
  { name: "Ecuador", short: "EC", code: "+593" },
  { name: "Egypt", short: "EG", code: "+20" },
  { name: "El Salvador", short: "SV", code: "+503" },
  { name: "Equatorial Guinea", short: "GQ", code: "+240" },
  { name: "Eritrea", short: "ER", code: "+291" },
  { name: "Estonia", short: "EE", code: "+372" },
  { name: "Eswatini", short: "SZ", code: "+268" },
  { name: "Ethiopia", short: "ET", code: "+251" },
  { name: "Falkland Islands", short: "FK", code: "+500" },
  { name: "Faroe Islands", short: "FO", code: "+298" },
  { name: "Fiji", short: "FJ", code: "+679" },
  { name: "Finland", short: "FI", code: "+358" },
  { name: "France", short: "FR", code: "+33" },
  { name: "French Guiana", short: "GF", code: "+594" },
  { name: "French Polynesia", short: "PF", code: "+689" },
  { name: "Gabon", short: "GA", code: "+241" },
  { name: "Gambia", short: "GM", code: "+220" },
  { name: "Georgia", short: "GE", code: "+995" },
  { name: "Germany", short: "DE", code: "+49" },
  { name: "Ghana", short: "GH", code: "+233" },
  { name: "Gibraltar", short: "GI", code: "+350" },
  { name: "Greece", short: "GR", code: "+30" },
  { name: "Greenland", short: "GL", code: "+299" },
  { name: "Grenada", short: "GD", code: "+1" },
  { name: "Guadeloupe", short: "GP", code: "+590" },
  { name: "Guam", short: "GU", code: "+1" },
  { name: "Guatemala", short: "GT", code: "+502" },
  { name: "Guinea", short: "GN", code: "+224" },
  { name: "Guinea-Bissau", short: "GW", code: "+245" },
  { name: "Guyana", short: "GY", code: "+592" },
  { name: "Haiti", short: "HT", code: "+509" },
  { name: "Honduras", short: "HN", code: "+504" },
  { name: "Hong Kong", short: "HK", code: "+852" },
  { name: "Hungary", short: "HU", code: "+36" },
  { name: "Iceland", short: "IS", code: "+354" },
  { name: "India", short: "IN", code: "+91" },
  { name: "Indonesia", short: "ID", code: "+62" },
  { name: "Iran", short: "IR", code: "+98" },
  { name: "Iraq", short: "IQ", code: "+964" },
  { name: "Ireland", short: "IE", code: "+353" },
  { name: "Israel", short: "IL", code: "+972" },
  { name: "Italy", short: "IT", code: "+39" },
  { name: "Ivory Coast", short: "CI", code: "+225" },
  { name: "Jamaica", short: "JM", code: "+1" },
  { name: "Japan", short: "JP", code: "+81" },
  { name: "Jordan", short: "JO", code: "+962" },
  { name: "Kazakhstan", short: "KZ", code: "+7" },
  { name: "Kenya", short: "KE", code: "+254" },
  { name: "Kiribati", short: "KI", code: "+686" },
  { name: "Kosovo", short: "XK", code: "+383" },
  { name: "Kuwait", short: "KW", code: "+965" },
  { name: "Kyrgyzstan", short: "KG", code: "+996" },
  { name: "Laos", short: "LA", code: "+856" },
  { name: "Latvia", short: "LV", code: "+371" },
  { name: "Lebanon", short: "LB", code: "+961" },
  { name: "Lesotho", short: "LS", code: "+266" },
  { name: "Liberia", short: "LR", code: "+231" },
  { name: "Libya", short: "LY", code: "+218" },
  { name: "Liechtenstein", short: "LI", code: "+423" },
  { name: "Lithuania", short: "LT", code: "+370" },
  { name: "Luxembourg", short: "LU", code: "+352" },
  { name: "Macau", short: "MO", code: "+853" },
  { name: "Madagascar", short: "MG", code: "+261" },
  { name: "Malawi", short: "MW", code: "+265" },
  { name: "Malaysia", short: "MY", code: "+60" },
  { name: "Maldives", short: "MV", code: "+960" },
  { name: "Mali", short: "ML", code: "+223" },
  { name: "Malta", short: "MT", code: "+356" },
  { name: "Marshall Islands", short: "MH", code: "+692" },
  { name: "Martinique", short: "MQ", code: "+596" },
  { name: "Mauritania", short: "MR", code: "+222" },
  { name: "Mauritius", short: "MU", code: "+230" },
  { name: "Mayotte", short: "YT", code: "+262" },
  { name: "Mexico", short: "MX", code: "+52" },
  { name: "Micronesia", short: "FM", code: "+691" },
  { name: "Moldova", short: "MD", code: "+373" },
  { name: "Monaco", short: "MC", code: "+377" },
  { name: "Mongolia", short: "MN", code: "+976" },
  { name: "Montenegro", short: "ME", code: "+382" },
  { name: "Montserrat", short: "MS", code: "+1" },
  { name: "Morocco", short: "MA", code: "+212" },
  { name: "Mozambique", short: "MZ", code: "+258" },
  { name: "Myanmar", short: "MM", code: "+95" },
  { name: "Namibia", short: "NA", code: "+264" },
  { name: "Nauru", short: "NR", code: "+674" },
  { name: "Nepal", short: "NP", code: "+977" },
  { name: "Netherlands", short: "NL", code: "+31" },
  { name: "New Caledonia", short: "NC", code: "+687" },
  { name: "New Zealand", short: "NZ", code: "+64" },
  { name: "Nicaragua", short: "NI", code: "+505" },
  { name: "Niger", short: "NE", code: "+227" },
  { name: "Nigeria", short: "NG", code: "+234" },
  { name: "Niue", short: "NU", code: "+683" },
  { name: "North Korea", short: "KP", code: "+850" },
  { name: "North Macedonia", short: "MK", code: "+389" },
  { name: "Northern Mariana Islands", short: "MP", code: "+1" },
  { name: "Norway", short: "NO", code: "+47" },
  { name: "Oman", short: "OM", code: "+968" },
  { name: "Pakistan", short: "PK", code: "+92" },
  { name: "Palau", short: "PW", code: "+680" },
  { name: "Palestine", short: "PS", code: "+970" },
  { name: "Panama", short: "PA", code: "+507" },
  { name: "Papua New Guinea", short: "PG", code: "+675" },
  { name: "Paraguay", short: "PY", code: "+595" },
  { name: "Peru", short: "PE", code: "+51" },
  { name: "Philippines", short: "PH", code: "+63" },
  { name: "Poland", short: "PL", code: "+48" },
  { name: "Portugal", short: "PT", code: "+351" },
  { name: "Puerto Rico", short: "PR", code: "+1" },
  { name: "Qatar", short: "QA", code: "+974" },
  { name: "Reunion", short: "RE", code: "+262" },
  { name: "Romania", short: "RO", code: "+40" },
  { name: "Russia", short: "RU", code: "+7" },
  { name: "Rwanda", short: "RW", code: "+250" },
  { name: "Saint Helena", short: "SH", code: "+290" },
  { name: "Saint Kitts and Nevis", short: "KN", code: "+1" },
  { name: "Saint Lucia", short: "LC", code: "+1" },
  { name: "Saint Pierre and Miquelon", short: "PM", code: "+508" },
  { name: "Saint Vincent and the Grenadines", short: "VC", code: "+1" },
  { name: "Samoa", short: "WS", code: "+685" },
  { name: "San Marino", short: "SM", code: "+378" },
  { name: "Sao Tome and Principe", short: "ST", code: "+239" },
  { name: "Saudi Arabia", short: "SA", code: "+966" },
  { name: "Senegal", short: "SN", code: "+221" },
  { name: "Serbia", short: "RS", code: "+381" },
  { name: "Seychelles", short: "SC", code: "+248" },
  { name: "Sierra Leone", short: "SL", code: "+232" },
  { name: "Singapore", short: "SG", code: "+65" },
  { name: "Slovakia", short: "SK", code: "+421" },
  { name: "Slovenia", short: "SI", code: "+386" },
  { name: "Solomon Islands", short: "SB", code: "+677" },
  { name: "Somalia", short: "SO", code: "+252" },
  { name: "South Africa", short: "ZA", code: "+27" },
  { name: "South Korea", short: "KR", code: "+82" },
  { name: "South Sudan", short: "SS", code: "+211" },
  { name: "Spain", short: "ES", code: "+34" },
  { name: "Sri Lanka", short: "LK", code: "+94" },
  { name: "Sudan", short: "SD", code: "+249" },
  { name: "Suriname", short: "SR", code: "+597" },
  { name: "Sweden", short: "SE", code: "+46" },
  { name: "Switzerland", short: "CH", code: "+41" },
  { name: "Syria", short: "SY", code: "+963" },
  { name: "Taiwan", short: "TW", code: "+886" },
  { name: "Tajikistan", short: "TJ", code: "+992" },
  { name: "Tanzania", short: "TZ", code: "+255" },
  { name: "Thailand", short: "TH", code: "+66" },
  { name: "Timor-Leste", short: "TL", code: "+670" },
  { name: "Togo", short: "TG", code: "+228" },
  { name: "Tokelau", short: "TK", code: "+690" },
  { name: "Tonga", short: "TO", code: "+676" },
  { name: "Trinidad and Tobago", short: "TT", code: "+1" },
  { name: "Tunisia", short: "TN", code: "+216" },
  { name: "Turkey", short: "TR", code: "+90" },
  { name: "Turkmenistan", short: "TM", code: "+993" },
  { name: "Turks and Caicos Islands", short: "TC", code: "+1" },
  { name: "Tuvalu", short: "TV", code: "+688" },
  { name: "U.S. Virgin Islands", short: "VI", code: "+1" },
  { name: "Uganda", short: "UG", code: "+256" },
  { name: "Ukraine", short: "UA", code: "+380" },
  { name: "United Arab Emirates", short: "AE", code: "+971" },
  { name: "United Kingdom", short: "GB", code: "+44" },
  { name: "United States", short: "US", code: "+1" },
  { name: "Uruguay", short: "UY", code: "+598" },
  { name: "Uzbekistan", short: "UZ", code: "+998" },
  { name: "Vanuatu", short: "VU", code: "+678" },
  { name: "Vatican City", short: "VA", code: "+39" },
  { name: "Venezuela", short: "VE", code: "+58" },
  { name: "Vietnam", short: "VN", code: "+84" },
  { name: "Wallis and Futuna", short: "WF", code: "+681" },
  { name: "Yemen", short: "YE", code: "+967" },
  { name: "Zambia", short: "ZM", code: "+260" },
  { name: "Zimbabwe", short: "ZW", code: "+263" },
];

export default COUNTRY_CODES;
